services:
  immich-public-proxy:
    image: alangrainger/immich-public-proxy:latest
    container_name: immich-public-proxy
    restart: always
    ports:
      - ${PORT}:3000
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    healthcheck:
      test: ([ "$(wget -qO- ${PROXY_PUBLIC_URL}/healthcheck)" = "ok" ] && exit 0) || exit 1
      interval: 120s
      start_period: 5s
