services:
  immich-public-proxy:
    image: alangrainger/immich-public-proxy:latest
    container_name: immich-public-proxy
    restart: always
    ports:
      - ${PORT}:3000
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./config.json:/app/config.json:ro
    healthcheck:
      test: node /app/healthcheck.js
      interval: 120s
      start_period: 5s
