services:
  immich-public-proxy:
    image: ghcr.io/alangrainger/immich-public-proxy:latest
    container_name: immich-public-proxy
    restart: unless-stopped
    ports:
      - ${PORT}:3000
    environment:
      - NODE_ENV=production
    env_file:
      - .env


