services:
  immich-public-proxy:
    image: alangrainger/immich-public-proxy:latest
    container_name: immich-public-proxy
    restart: always
    ports:
      - ${PORT}:3000
    env_file: .env
    healthcheck:
      test: wget -q http://localhost:3000/healthcheck || exit 1
      start_period: 10s
      timeout: 5s
