services:
  immich-public-proxy:
    image: alangrainger/immich-public-proxy:latest
    container_name: immich-public-proxy
    restart: always
    ports:
      - ${PORT}:3000
    env_file: .env
    healthcheck:
      test: node /app/healthcheck.js
      interval: 30s
      start_period: 10s
